Fix possible AttributeError: 'NoneType' object has no attribute 'remove' on terminal close
Add missed after_idle(terminate_process) instead of plain terminate_process on terminal close.