Fix rare possible error on closing buffer
Fixed a rare possible AttributeError: NoneType has no attribute 'remove' on closing an editor / terminal / email buffer because of a previously scheduled function trying to operate on a destroyed widget.